version: '3.8'
services:
  php:
    container_name: php
    restart: on-failure
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www:rw,cached
    entrypoint: ["/bin/sh", "-c", "composer install --no-scripts --no-interaction && bin/console cache:clear && yarn install && yarn encore dev && php-fpm"]

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www:rw,cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
